// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum type
type ExampleTypes_ExampleEnum int32

const (
	ExampleTypes_UNKNOWN    ExampleTypes_ExampleEnum = 0
	ExampleTypes_OPTION_ONE ExampleTypes_ExampleEnum = 1
	ExampleTypes_OPTION_TWO ExampleTypes_ExampleEnum = 2
)

// Enum value maps for ExampleTypes_ExampleEnum.
var (
	ExampleTypes_ExampleEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "OPTION_ONE",
		2: "OPTION_TWO",
	}
	ExampleTypes_ExampleEnum_value = map[string]int32{
		"UNKNOWN":    0,
		"OPTION_ONE": 1,
		"OPTION_TWO": 2,
	}
)

func (x ExampleTypes_ExampleEnum) Enum() *ExampleTypes_ExampleEnum {
	p := new(ExampleTypes_ExampleEnum)
	*p = x
	return p
}

func (x ExampleTypes_ExampleEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleTypes_ExampleEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ExampleTypes_ExampleEnum) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ExampleTypes_ExampleEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleTypes_ExampleEnum.Descriptor instead.
func (ExampleTypes_ExampleEnum) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0, 0}
}

// Message demonstrating various Protobuf field types.
type ExampleTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Scalar types
	IntField    int32                    `protobuf:"varint,1,opt,name=int_field,json=intField,proto3" json:"int_field,omitempty"`                                        // An integer field
	FloatField  float32                  `protobuf:"fixed32,2,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`                                 // A floating point field
	DoubleField float64                  `protobuf:"fixed64,3,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`                              // A double precision floating point field
	StringField string                   `protobuf:"bytes,4,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`                                // A string field
	BoolField   bool                     `protobuf:"varint,5,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`                                     // A boolean field
	BytesField  []byte                   `protobuf:"bytes,6,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`                                   // A field for raw bytes
	EnumField   ExampleTypes_ExampleEnum `protobuf:"varint,7,opt,name=enum_field,json=enumField,proto3,enum=types.ExampleTypes_ExampleEnum" json:"enum_field,omitempty"` // An enum field
	// Repeated (array) fields
	RepeatedIntField []int32 `protobuf:"varint,8,rep,packed,name=repeated_int_field,json=repeatedIntField,proto3" json:"repeated_int_field,omitempty"` // A repeated field (like an array) for integers
	// Map fields
	MapField      map[string]int32            `protobuf:"bytes,9,rep,name=map_field,json=mapField,proto3" json:"map_field,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // A map field, mapping from string to int
	NestedMessage *ExampleTypes_NestedMessage `protobuf:"bytes,10,opt,name=nested_message,json=nestedMessage,proto3" json:"nested_message,omitempty"`                                                                          // A nested message field
	// Oneof field
	//
	// Types that are assignable to TestOneof:
	//
	//	*ExampleTypes_OneofString
	//	*ExampleTypes_OneofInt
	TestOneof isExampleTypes_TestOneof `protobuf_oneof:"test_oneof"`
	// Example of a new field added later
	NewField string `protobuf:"bytes,14,opt,name=new_field,json=newField,proto3" json:"new_field,omitempty"`
}

func (x *ExampleTypes) Reset() {
	*x = ExampleTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleTypes) ProtoMessage() {}

func (x *ExampleTypes) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleTypes.ProtoReflect.Descriptor instead.
func (*ExampleTypes) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleTypes) GetIntField() int32 {
	if x != nil {
		return x.IntField
	}
	return 0
}

func (x *ExampleTypes) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *ExampleTypes) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *ExampleTypes) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *ExampleTypes) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *ExampleTypes) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

func (x *ExampleTypes) GetEnumField() ExampleTypes_ExampleEnum {
	if x != nil {
		return x.EnumField
	}
	return ExampleTypes_UNKNOWN
}

func (x *ExampleTypes) GetRepeatedIntField() []int32 {
	if x != nil {
		return x.RepeatedIntField
	}
	return nil
}

func (x *ExampleTypes) GetMapField() map[string]int32 {
	if x != nil {
		return x.MapField
	}
	return nil
}

func (x *ExampleTypes) GetNestedMessage() *ExampleTypes_NestedMessage {
	if x != nil {
		return x.NestedMessage
	}
	return nil
}

func (m *ExampleTypes) GetTestOneof() isExampleTypes_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *ExampleTypes) GetOneofString() string {
	if x, ok := x.GetTestOneof().(*ExampleTypes_OneofString); ok {
		return x.OneofString
	}
	return ""
}

func (x *ExampleTypes) GetOneofInt() int32 {
	if x, ok := x.GetTestOneof().(*ExampleTypes_OneofInt); ok {
		return x.OneofInt
	}
	return 0
}

func (x *ExampleTypes) GetNewField() string {
	if x != nil {
		return x.NewField
	}
	return ""
}

type isExampleTypes_TestOneof interface {
	isExampleTypes_TestOneof()
}

type ExampleTypes_OneofString struct {
	OneofString string `protobuf:"bytes,11,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

type ExampleTypes_OneofInt struct {
	OneofInt int32 `protobuf:"varint,12,opt,name=oneof_int,json=oneofInt,proto3,oneof"`
}

func (*ExampleTypes_OneofString) isExampleTypes_TestOneof() {}

func (*ExampleTypes_OneofInt) isExampleTypes_TestOneof() {}

// Nested message
type ExampleTypes_NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NestedField string `protobuf:"bytes,1,opt,name=nested_field,json=nestedField,proto3" json:"nested_field,omitempty"` // A nested field within a nested message
}

func (x *ExampleTypes_NestedMessage) Reset() {
	*x = ExampleTypes_NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleTypes_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleTypes_NestedMessage) ProtoMessage() {}

func (x *ExampleTypes_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleTypes_NestedMessage.ProtoReflect.Descriptor instead.
func (*ExampleTypes_NestedMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ExampleTypes_NestedMessage) GetNestedField() string {
	if x != nil {
		return x.NestedField
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

var file_types_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x22, 0x90, 0x06, 0x0a, 0x0c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f,
	0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62,
	0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3e, 0x0a, 0x0a, 0x65, 0x6e, 0x75,
	0x6d, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09,
	0x65, 0x6e, 0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49,
	0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3e, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d,
	0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x48, 0x0a, 0x0e, 0x6e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x0d, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x23, 0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x6e, 0x65, 0x6f, 0x66,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x09, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f,
	0x69, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x6e, 0x65,
	0x6f, 0x66, 0x49, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x32, 0x0a, 0x0d, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0x3a, 0x0a, 0x0b, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x57, 0x4f, 0x10, 0x02, 0x42,
	0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x4a, 0x04, 0x08,
	0x0d, 0x10, 0x0e, 0x4a, 0x04, 0x08, 0x0f, 0x10, 0x10, 0x4a, 0x04, 0x08, 0x10, 0x10, 0x11, 0x4a,
	0x04, 0x08, 0x14, 0x10, 0x1f, 0x52, 0x10, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData = file_types_proto_rawDesc
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_proto_rawDescData)
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_types_proto_goTypes = []interface{}{
	(ExampleTypes_ExampleEnum)(0),      // 0: types.ExampleTypes.ExampleEnum
	(*ExampleTypes)(nil),               // 1: types.ExampleTypes
	nil,                                // 2: types.ExampleTypes.MapFieldEntry
	(*ExampleTypes_NestedMessage)(nil), // 3: types.ExampleTypes.NestedMessage
}
var file_types_proto_depIdxs = []int32{
	0, // 0: types.ExampleTypes.enum_field:type_name -> types.ExampleTypes.ExampleEnum
	2, // 1: types.ExampleTypes.map_field:type_name -> types.ExampleTypes.MapFieldEntry
	3, // 2: types.ExampleTypes.nested_message:type_name -> types.ExampleTypes.NestedMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleTypes_NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_types_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ExampleTypes_OneofString)(nil),
		(*ExampleTypes_OneofInt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_rawDesc = nil
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
